version: '3'
services:
    jupyter:
        image: jupyter/datascience-notebook:latest
        restart: 'no'
        volumes:
            - ./notebook:/home/jovyan/
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=yes
